apiVersion: v1
kind: Service
metadata:
  name: financial-monitor-service
spec:
  selector:
    app: financial-monitor
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000